name = "GARComp"
uuid = "c623fb47-a506-4f81-a1c5-224f929d029f"
authors = ["pvpisistratus <pvpisistratus@gmail.com> and contributors"]
version = "0.1.0"

[deps]
GameZero = "9da27670-f782-11e9-1da1-f53579315bfe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
